

    export const ALL_SKILLS: string[] = [
    // Communication Skills
    'Clear Communication',
    'Active Listening',
    'Professional Language',
    'Multilingual',
    'Client Consultation',
    'Explaining Technical Terms',
    'Phone Etiquette',
    'Written Communication',
    'Non-Verbal Communication',
    'Conflict Resolution',

    // Customer Service Skills
    'Customer Focus',
    'Patience',
    'Empathy',
    'Professional Demeanor',
    'Problem-Solving Attitude',
    'Service Orientation',
    'Client Relationship Management',
    'Customer Satisfaction Focus',
    'Complaint Handling',
    'Follow-up Service',

    // Professionalism
    'Punctuality',
    'Reliability',
    'Professional Appearance',
    'Work Ethic',
    'Integrity',
    'Confidentiality',
    'Respect for Property',
    'Clean Work Habits',
    'Time Management',
    'Accountability',

    // Technical & Problem-Solving Skills
    'Technical Knowledge',
    'Attention to Detail',
    'Analytical Thinking',
    'Troubleshooting',
    'Quality Focus',
    'Safety Consciousness',
    'Precision Work',
    'Technical Adaptability',
    'Equipment Knowledge',
    'Standards Compliance',

    // Teamwork & Collaboration
    'Team Player',
    'Collaboration',
    'Mentoring',
    'Coordination',
    'Interpersonal Skills',
    'Leadership',
    'Supervision',
    'Delegation',
    'Cross-functional Coordination',
    'Conflict Management',

    // Adaptability & Learning
    'Adaptability',
    'Quick Learning',
    'Technology Adoption',
    'Process Improvement',
    'Continuous Learning',
    'Flexibility',
    'Stress Management',
    'Multitasking',
    'Open to Feedback',
    'Innovative Thinking',

    // Business Skills
    'Cost Estimation',
    'Budget Management',
    'Material Planning',
    'Resource Management',
    'Project Management',
    'Documentation',
    'Record Keeping',
    'Quoting Skills',
    'Inventory Management',
    'Quality Control',

    // Safety & Compliance
    'Safety Protocols',
    'Risk Assessment',
    'Emergency Response',
    'Regulatory Compliance',
    'Safety Training',
    'Equipment Safety',
    'Site Safety',
    'First Aid Certified',
    'Environmental Awareness',
    'Hazard Identification',

    // Physical & Personal Skills
    'Physical Stamina',
    'Manual Dexterity',
    'Hand-eye Coordination',
    'Strength',
    'Endurance',
    'Spatial Awareness',
    'Color Vision',
    'Height Work Comfort',
    'Confined Space Work',
    'Weather Tolerance',

    // Digital Literacy
    'Mobile App Usage',
    'Digital Documentation',
    'Online Booking Management',
    'Digital Payments',
    'GPS Navigation',
    'Photo Documentation',
    'Email Communication',
    'Digital Reporting',
    'Online Training',
    'Social Media Professionalism',

    // Specialized Professional Skills
    'Estimation Accuracy',
    'Waste Management',
    'Energy Efficiency',
    'Sustainable Practices',
    'Code Compliance',
    'Permit Knowledge',
    'Inspection Readiness',
    'Warranty Management',
    'Guarantee Provision',
    'After-Sales Service',

    // Language & Cultural Skills
    'Local Language Proficiency',
    'Cultural Sensitivity',
    'Age Group Adaptation',
    'Gender Sensitivity',
    'Disability Awareness',
    'Privacy Respect',
    'Cultural Norms Understanding',
    'Local Regulations Knowledge',
    'Community Engagement',
    'Regional Expertise',

    // Certifications & Qualifications
    'Licensed Professional',
    'Certified Technician',
    'Insurance Coverage',
    'Background Verified',
    'Training Certified',
    'Apprenticeship Completed',
    'Trade School Graduate',
    'Experience Verified',
    'Reference Available',
    'Portfolio Showcase',

    // Personal Attributes
    'Trustworthy',
    'Honest',
    'Dependable',
    'Courteous',
    'Polite',
    'Friendly',
    'Respectful',
    'Patient',
    'Calm Under Pressure',
    'Positive Attitude',

    // Work Methodology
    'Systematic Approach',
    'Efficient Workflow',
    'Quality Assurance',
    'Double-checking',
    'Clean Workspace',
    'Tool Organization',
    'Material Conservation',
    'Waste Reduction',
    'Energy Conservation',
    'Sustainable Methods',

    // Communication Specifics
    'Clear Instructions',
    'Progress Updates',
    'Transparent Pricing',
    'Honest Timelines',
    'Regular Follow-ups',
    'Feedback Acceptance',
    'Question Encouragement',
    'Technical Translation',
    'Visual Demonstrations',
    'Written Confirmations',
  ];

